<div id=solsortEntries>
<a href="/next">
<div>next</div>
</a>
<a href="/test">
<div>test</div>
</a>
<a href="/contango">
<div>contango</div>
</a>
<a href="/404">
<div>404</div>
</a>
<a href="/2017-04-11-generic-backend-server">
<div>2017 04 11 generic backend server</div>
</a>
<a href="/2017-04-11-future-proof-webapps">
<div>2017 04 11 future proof webapps</div>
</a>
<a href="/2017-04-10-simple-javascript">
<div>2017 04 10 simple javascript</div>
</a>
<a href="/2017-03-09-building-for-the-future-broweser">
<div>2017 03 09 building for the future broweser</div>
</a>
<a href="/2017-03-02-herkules">
<div>2017 03 02 herkules</div>
</a>
<a href="/2017-02-27-www.solsort.com-landing-page">
<div>2017 02 27 www.solsort.com landing page</div>
</a>
<a href="/2017-02-08-user-interfaces-as-pure-json-data">
<div>2017 02 08 user interfaces as pure json data</div>
</a>
<a href="/2017-02-08-shell-ipfs-notes">
<div>2017 02 08 shell ipfs notes</div>
</a>
<a href="/2017-01-31-thoughts-about-distributed-cloud">
<div>2017 01 31 thoughts about distributed cloud</div>
</a>
<a href="/2017-01-25-copenhagen">
<div>2017 01 25 copenhagen</div>
</a>
<a href="/2017-01-15-my-startup">
<div>2017 01 15 my startup</div>
</a>
<a href="/2017-01-15-linux-mac-keyboard">
<div>2017 01 15 linux mac keyboard</div>
</a>
<a href="/2017-01-11-deploying-with-github-travis-and-unpkg">
<div>2017 01 11 deploying with github travis and unpkg</div>
</a>
<a href="/2016-12-30-my-calendar-early-2017">
<div>2016 12 30 my calendar early 2017</div>
</a>
<a href="/2016-12-29-metode-til-daglig-motion">
<div>2016 12 29 metode til daglig motion</div>
</a>
<a href="/2016-12-29-javascript-features-in-modern-browsers-2016">
<div>2016 12 29 javascript features in modern browsers 2016</div>
</a>
<a href="/2016-12-22-review-2016-direction-2017">
<div>2016 12 22 review 2016 direction 2017</div>
</a>
<a href="/2016-12-21-bootstrapped-clojurescript">
<div>2016 12 21 bootstrapped clojurescript</div>
</a>
<a href="/2016-12-15-extending-others-webservices">
<div>2016 12 15 extending others webservices</div>
</a>
<a href="/2016-12-05-blog-editor-notes">
<div>2016 12 05 blog editor notes</div>
</a>
<a href="/2016-11-20-data-calculator">
<div>2016 11 20 data calculator</div>
</a>
<a href="/2016-11-19-virtual-machine-revisited">
<div>2016 11 19 virtual machine revisited</div>
</a>
<a href="/2016-11-16-virtual-machine-memory-layout-for-a-functional-language-for-embedded-systems">
<div>2016 11 16 virtual machine memory layout for a functional language for embedded systems</div>
</a>
<a href="/2016-11-16-setting-up-android-development-react-native-under-linux">
<div>2016 11 16 setting up android development react native under linux</div>
</a>
<a href="/2016-11-15-important-javascript-features">
<div>2016 11 15 important javascript features</div>
</a>
<a href="/2016-10-20-bibliotekernes-udviklernetvaerksmode">
<div>2016 10 20 bibliotekernes udviklernetvaerksmode</div>
</a>
<a href="/2017/04/11/generic-backend-server/">
<div>2017 04 11 Generic backend server </div>
</a>
<a href="/2017/04/11/future-proof-webapps/">
<div>2017 04 11 Future Proof Apps </div>
</a>
<a href="/2017/04/10/simple-javascript/">
<div>2017 04 10 Simple JavaScript </div>
</a>
<a href="/2017/03/09/building-for-the-future-broweser/">
<div>2017 03 09 Building for the future browser </div>
</a>
<a href="/2017/03/02/herkules/">
<div>2017 03 02 Herakles </div>
</a>
<a href="/2017/02/27/www.solsort.com-landing-page/">
<div>2017 02 27 www.solsort.com landing page </div>
</a>
<a href="/2017/02/08/user-interfaces-as-pure-json-data/">
<div>2017 02 08 User interfaces as pure JSON data </div>
</a>
<a href="/2017/02/08/shell-ipfs-notes/">
<div>2017 02 08 Shell/ipfs notes </div>
</a>
<a href="/2017/01/31/thoughts-about-distributed-cloud/">
<div>2017 01 31 Thoughts about distributed cloud </div>
</a>
<a href="/2017/01/25/copenhagen/">
<div>2017 01 25 Copenhagen </div>
</a>
<a href="/2017/01/15/my-startup/">
<div>2017 01 15 My StartUp </div>
</a>
<a href="/2017/01/15/linux-mac-keyboard/">
<div>2017 01 15 Linux mac-keyboard map </div>
</a>
<a href="/2017/01/11/deploying-with-github-travis-and-unpkg/">
<div>2017 01 11 Releasing with github, travis and unpkg. </div>
</a>
<a href="/2016/12/30/my-calendar-early-2017/">
<div>2016 12 30 My calendar - early 2017 </div>
</a>
<a href="/2016/12/29/metode-til-daglig-motion/">
<div>2016 12 29 Metode til daglig motion </div>
</a>
<a href="/2016/12/29/javascript-features-in-modern-browsers-2016/">
<div>2016 12 29 JavaScript features in modern browsers 2016 </div>
</a>
<a href="/2016/12/22/review-2016-direction-2017/">
<div>2016 12 22 Review 2016 / Direction 2017 </div>
</a>
<a href="/2016/12/21/bootstrapped-clojurescript/">
<div>2016 12 21 Bootstrapped ClojureScript </div>
</a>
<a href="/2016/12/15/extending-others-webservices/">
<div>2016 12 15 Extending others webservices </div>
</a>
<a href="/2016/12/04/blog-editor-notes/">
<div>2016 12 04 Blog Editor Notes </div>
</a>
<a href="/2016/11/20/data-calculator/">
<div>2016 11 20 Data Calculator User Interaction </div>
</a>
<a href="/2016/11/19/virtual-machine-revisited/">
<div>2016 11 19 Virtual machine, - revisited </div>
</a>
<a href="/2016/11/16/virtual-machine-memory-layout-for-a-functional-language-for-embedded-systems/">
<div>2016 11 16 Virtual Machine Memory Layout for a Functional Language for Embedded Systems </div>
</a>
<a href="/2016/11/16/setting-up-android-development-react-native-under-linux/">
<div>2016 11 16 Setting up Android development / React Native under Linux </div>
</a>
<a href="/2016/11/15/important-javascript-features/">
<div>2016 11 15 Important JavaScript Features </div>
</a>
<a href="/2016/10/20/bibliotekernes-udviklernetvaerksmode/">
<div>2016 10 20 Bibliotekernes udviklernetværksmøde </div>
</a>
<a href="/2016/08/11/fokus/">
<div>2016 08 11 Fokus </div>
</a>
<a href="/2016/07/25/laering/">
<div>2016 07 25 Læring </div>
</a>
<a href="/2016/07/15/decentrale-apps/">
<div>2016 07 15 Decentrale apps </div>
</a>
<a href="/2016/07/07/on-god/">
<div>2016 07 07 On God </div>
</a>
<a href="/2016/07/07/why-i-write/">
<div>2016 07 07 Why I write </div>
</a>
<a href="/2016/07/06/productivity-tools/">
<div>2016 07 06 Productivity tools </div>
</a>
<a href="/2016/07/06/improvisation/">
<div>2016 07 06 Improvisation </div>
</a>
<a href="/2016/07/03/iliaden/">
<div>2016 07 03 Iliaden </div>
</a>
<a href="/2016/06/30/quarterly-review-2016q2/">
<div>2016 06 30 Quarterly review 2016q2 </div>
</a>
<a href="/2016/06/27/tools-for-text-editing/">
<div>2016 06 27 Tools for text editing </div>
</a>
<a href="/2016/06/08/narrow-vs-wide/">
<div>2016 06 08 Narrow vs wide </div>
</a>
<a href="/2016/06/07/habitica-backup/">
<div>2016 06 07 Habitica backup </div>
</a>
<a href="/2016/06/05/owncloud-and-docker/">
<div>2016 06 05 OwnCloud and Docker </div>
</a>
<a href="/2016/06/04/abcd-treat/">
<div>2016 06 04 ABCD-treat </div>
</a>
<a href="/2016/06/02/my-projects/">
<div>2016 06 02 My &#8220;projects&#8221; </div>
</a>
<a href="/2016/06/01/a-life-on-four-pages/">
<div>2016 06 01 A life on four pages </div>
</a>
<a href="/2016/05/07/month-of-work-and-son/">
<div>2016 05 07 Month of work and son </div>
</a>
<a href="/2016/05/03/experience-with-caddy-webserver/">
<div>2016 05 03 Experience with Caddy webserver </div>
</a>
<a href="/2016/04/27/hours-vs-solutions/">
<div>2016 04 27 Hours vs solutions </div>
</a>
<a href="/2016/04/25/dimensions-of-life/">
<div>2016 04 25 Dimensions of life </div>
</a>
<a href="/2016/04/21/trie-performance/">
<div>2016 04 21 Trie performance </div>
</a>
<a href="/2016/04/21/vision-for-life/">
<div>2016 04 21 Vision for life </div>
</a>
<a href="/2016/04/18/straight-forward/">
<div>2016 04 18 Straight forward </div>
</a>
<a href="/2016/04/17/mobibl/">
<div>2016 04 17 Mobibl </div>
</a>
<a href="/2016/04/17/current-projects/">
<div>2016 04 17 Current projects </div>
</a>
<a href="/2016/04/16/discipline-and-flow/">
<div>2016 04 16 Discipline and flow </div>
</a>
<a href="/2016/04/13/mythology-ownership/">
<div>2016 04 13 Mythology ownership </div>
</a>
<a href="/2016/04/09/notes-about-a-distributed-database-design/">
<div>2016 04 09 Notes about a distributed database design </div>
</a>
<a href="/2016/04/08/varying-intensity/">
<div>2016 04 08 Varying intensity </div>
</a>
<a href="/2016/04/06/server-set-up-caddy-and-docker/">
<div>2016 04 06 Server set up: Caddy and Docker </div>
</a>
<a href="/2016/04/05/probabilistic-sorting/">
<div>2016 04 05 Probabilistic sorting </div>
</a>
<a href="/2016/04/04/start-nu-bare/">
<div>2016 04 04 Start nu bare </div>
</a>
<a href="/2016/04/03/luck-notes-and-just-do-it/">
<div>2016 04 03 Luck, notes, and just do it </div>
</a>
<a href="/2016/04/03/writing-subjects/">
<div>2016 04 03 Writing subjects </div>
</a>
<a href="/2016/04/02/pen-and-paper-role-playing-a-heavily-optimised-cleric-build/">
<div>2016 04 02 Pen-and-paper role playing: A heavily optimised cleric build </div>
</a>
<a href="/2016/04/01/identitetsniveauer/">
<div>2016 04 01 Identitetsniveauer </div>
</a>
<a href="/2016/03/31/1-2-3-priority/">
<div>2016 03 31 1-2-3 priority </div>
</a>
<a href="/2016/03/31/kvartal/">
<div>2016 03 31 Kvartal </div>
</a>
<a href="/2016/03/30/solsort-direction/">
<div>2016 03 30 solsort direction </div>
</a>
<a href="/2016/03/29/morning-routine-challenge/">
<div>2016 03 29 Morning routine challenge </div>
</a>
<a href="/2016/03/29/benefits-from-writing/">
<div>2016 03 29 Benefits from writing </div>
</a>
<a href="/2016/03/28/hierarkisk-tid/">
<div>2016 03 28 Hierarkisk tid </div>
</a>
<a href="/2016/03/27/getting-back-to-writing/">
<div>2016 03 27 Getting back to writing </div>
</a>
<a href="/2016/03/27/mind-of-the-traveller/">
<div>2016 03 27 Mind of the traveller </div>
</a>
<a href="/2016/03/08/ninja-gig/">
<div>2016 03 08 Ninja Gig </div>
</a>
<a href="/2016/03/07/a-useful-question/">
<div>2016 03 07 A useful question. </div>
</a>
<a href="/2016/03/06/the-power-of-daily-the-checklist/">
<div>2016 03 06 The power of daily the checklist </div>
</a>
<a href="/2016/01/02/mobile-html5-react-libraries/">
<div>2016 01 02 Mobile HTML5 React libraries </div>
</a>
<a href="/2016/01/01/interesting-technologies/">
<div>2016 01 01 Interesting technologies </div>
</a>
<a href="/2015/12/30/tilbageblik-2015/">
<div>2015 12 30 Tilbageblik 2015 </div>
</a>
<a href="/2015/12/13/aarets-gang-og-retning/">
<div>2015 12 13 Årets gang, og retning </div>
</a>
<a href="/2015/11/18/data-json/">
<div>2015 11 18 Data JSON </div>
</a>
<a href="/2015/11/16/rethinking-bibapp/">
<div>2015 11 16 Rethinking BibApp </div>
</a>
<a href="/2015/11/15/idea-for-simplifying-authentication/">
<div>2015 11 15 Idea for simplifying authentication </div>
</a>
<a href="/2015/11/15/old-front-page-with-project-list/">
<div>2015 11 15 Old front-page with project list </div>
</a>
<a href="/2015/11/15/variable-byte-encoding-of-unsigned-integers/">
<div>2015 11 15 Variable byte encoding of unsigned integers. </div>
</a>
<a href="/2015/11/15/wordpress-theme-development/">
<div>2015 11 15 WordPress theme development </div>
</a>
<a href="/2015/11/14/lets-encrypt/">
<div>2015 11 14 Let&#8217;s encrypt! </div>
</a>
<a href="/2015/11/14/laptop-branding/">
<div>2015 11 14 Laptop branding </div>
</a>
<a href="/2015/11/14/word-order-in-programming-and-human-languages/">
<div>2015 11 14 Word order in programming and human languages </div>
</a>
<a href="/2015/11/13/swing-dancing-in-copenhagen/">
<div>2015 11 13 Swing dancing in Copenhagen </div>
</a>
<a href="/2015/10/20/mubackend-revisited/">
<div>2015 10 20 MuBackend revisited </div>
</a>
<a href="/2015/10/07/b-trie/">
<div>2015 10 07 B-trie </div>
</a>
<a href="/2015/10/02/the-3-day-sprint/">
<div>2015 10 02 The 3-day sprint </div>
</a>
<a href="/2015/10/02/no-screen-time-in-the-evening/">
<div>2015 10 02 No screen-time in the evening </div>
</a>
<a href="/2015/09/29/lemon-status-2/">
<div>2015 09 29 Lemon status 2 </div>
</a>
<a href="/2015/09/17/app-entry-point/">
<div>2015 09 17 App entry point </div>
</a>
<a href="/2015/09/15/projekt-lemon/">
<div>2015 09 15 Projekt Lemon </div>
</a>
<a href="/2015/09/11/checkliste-for-brunch/">
<div>2015 09 11 Checkliste for brunch </div>
</a>
<a href="/2015/09/10/async-loaded-figwheel-cljs/">
<div>2015 09 10 Async loaded figwheel cljs </div>
</a>
<a href="/2015/09/09/hack4dk-warmup/">
<div>2015 09 09 Hack4dk warmup </div>
</a>
<a href="/2015/09/08/solsort-widget-in-progress/">
<div>2015 09 08 solsort widget in progress </div>
</a>
<a href="/2015/09/07/lemon-status-1/">
<div>2015 09 07 Development structure, and Lemon status 1 </div>
</a>
<a href="/2015/09/06/getting-back-to-daily-writing/">
<div>2015 09 06 Getting back to daily writing. </div>
</a>
<a href="/2015/08/26/mubackend/">
<div>2015 08 26 MuBackend </div>
</a>
<a href="/2015/08/22/peer-app-notes/">
<div>2015 08 22 Peer app notes </div>
</a>
<a href="/2015/08/21/distracted-by-music/">
<div>2015 08 21 Distracted by music </div>
</a>
<a href="/2015/08/20/flow-and-focus/">
<div>2015 08 20 Flow and focus </div>
</a>
<a href="/2015/08/19/coding-habit/">
<div>2015 08 19 Coding habit </div>
</a>
<a href="/2015/08/18/responsive-base-app-design/">
<div>2015 08 18 Responsive base app design </div>
</a>
<a href="/2015/08/17/mobile-ui/">
<div>2015 08 17 Mobile UI </div>
</a>
<a href="/2015/08/16/associations-and-read-somedays-on-meta-thinking/">
<div>2015 08 16 Associations and read-somedays on meta-thinking </div>
</a>
<a href="/2015/08/15/half-monthly-review-2015-15/">
<div>2015 08 15 Half-monthly review 2015-15 </div>
</a>
<a href="/2015/08/14/learning/">
<div>2015 08 14 Learning </div>
</a>
<a href="/2015/08/13/thinking-about-literary-formats/">
<div>2015 08 13 Thinking about literary formats </div>
</a>
<a href="/2015/08/12/nfsm-synopsis/">
<div>2015 08 12 NFMS synopsis </div>
</a>
<a href="/2015/08/11/342/">
<div>2015 08 11 Writing direction </div>
</a>
<a href="/2015/08/10/borneboger-til-3-arig/">
<div>2015 08 10 Børnebøger til 3-årig </div>
</a>
<a href="/2015/08/09/the-power-of-music/">
<div>2015 08 09 The power of music </div>
</a>
<a href="/2015/08/08/aesops-fabler/">
<div>2015 08 08 Æsops fabler </div>
</a>
<a href="/2015/08/07/stream-of-consciousness/">
<div>2015 08 07 Stream of consciousness </div>
</a>
<a href="/2015/08/06/going-out/">
<div>2015 08 06 Going out </div>
</a>
<a href="/2015/08/05/194/">
<div>2015 08 05 Git workflow with github and waffle </div>
</a>
<a href="/2015/08/04/20-years-of-technology/">
<div>2015 08 04 20 years of technology </div>
</a>
<a href="/2015/08/03/216/">
<div>2015 08 03 Growing older </div>
</a>
<a href="/2015/08/02/keep-it-simple/">
<div>2015 08 02 Keep it simple </div>
</a>
<a href="/2015/08/01/easy-piano-blues/">
<div>2015 08 01 Easy piano blues </div>
</a>
<a href="/2015/07/31/planned-vs-improvised/">
<div>2015 07 31 Planned vs improvised </div>
</a>
<a href="/2015/07/30/game-mastering-and-making-stories/">
<div>2015 07 30 Game mastering, and making stories </div>
</a>
<a href="/2015/07/29/exercising/">
<div>2015 07 29 Exercising </div>
</a>
<a href="/2015/07/28/programmering-pa-skoleskemaet/">
<div>2015 07 28 Programmering på skoleskemaet </div>
</a>
<a href="/2015/07/27/wishlist-and-gifts/">
<div>2015 07 27 Wishlist, and gifts </div>
</a>
<a href="/2015/07/26/daily-writing-experiences/">
<div>2015 07 26 Daily writing experiences </div>
</a>
<a href="/2015/07/25/awareness-of-time/">
<div>2015 07 25 Awareness of time </div>
</a>
<a href="/2015/07/24/focus/">
<div>2015 07 24 Focus </div>
</a>
<a href="/2015/07/23/food-inventory/">
<div>2015 07 23 Food inventory </div>
</a>
<a href="/2015/07/21/checklist-and-food-for-throwing-a-party/">
<div>2015 07 21 Checklist and food for throwing a party </div>
</a>
<a href="/2015/07/20/spending-time-with-a-3-year-old/">
<div>2015 07 20 Spending time with a 3 year old </div>
</a>
<a href="/2015/07/19/configuration-management-tools/">
<div>2015 07 19 Configuration management tools </div>
</a>
<a href="/2015/07/18/solsort-backend-tech/">
<div>2015 07 18 Solsort backend tech </div>
</a>
<a href="/2015/07/17/why-wordpress/">
<div>2015 07 17 Why WordPress. </div>
</a>
<a href="/2015/07/16/tango-and-fusion/">
<div>2015 07 16 Tango fusion dance </div>
</a>
<a href="/2015/07/15/favourite-board-like-games/">
<div>2015 07 15 Favourite board-like games </div>
</a>
<a href="/2015/07/14/efficient-cooking/">
<div>2015 07 14 Efficient cooking </div>
</a>
<a href="/2015/07/13/record-yourself/">
<div>2015 07 13 Record yourself </div>
</a>
<a href="/2015/07/12/remember-yourself/">
<div>2015 07 12 Remember yourself </div>
</a>
<a href="/2015/07/11/being-a-father/">
<div>2015 07 11 Being a father </div>
</a>
<a href="/2015/07/10/solsort-com-technology-changes/">
<div>2015 07 10 solsort.com technology changes </div>
</a>
<a href="/2015/07/09/tech-videos-for-cooking-and-dishwashing/">
<div>2015 07 09 Tech videos for cooking and dishwashing </div>
</a>
<a href="/2015/07/08/pouchdb-get-internals/">
<div>2015 07 08 PouchDB .get internals </div>
</a>
<a href="/2015/07/07/web-data-storage/">
<div>2015 07 07 Web data storage </div>
</a>
<a href="/2015/07/06/falling-asleep/">
<div>2015 07 06 Falling asleep </div>
</a>
<a href="/2015/07/05/dress-style/">
<div>2015 07 05 Dress style </div>
</a>
<a href="/2015/07/04/milestone-reviews/">
<div>2015 07 04 Milestone reviews </div>
</a>
<a href="/2015/07/03/hierarchical-review/">
<div>2015 07 03 Hierarchical review </div>
</a>
<a href="/2015/07/02/summer-dance/">
<div>2015 07 02 Summer dance </div>
</a>
<a href="/2015/07/01/critically-non-urgent/">
<div>2015 07 01 Critically non-urgent </div>
</a>
<a href="/2015/06/30/github-shields-and-badges/">
<div>2015 06 30 GitHub shields and badges </div>
</a>
<a href="/2015/06/29/notes-about-chakras/">
<div>2015 06 29 Chakras </div>
</a>
<a href="/2015/06/28/email-processing/">
<div>2015 06 28 Email processing </div>
</a>
<a href="/2015/06/27/consuming-in-copenhagen/">
<div>2015 06 27 Consuming in Copenhagen </div>
</a>
<a href="/2015/06/26/programming-languages/">
<div>2015 06 26 Programming Languages </div>
</a>
<a href="/2015/06/25/death-and-the-source-of-self/">
<div>2015 06 25 Death, and the source of self </div>
</a>
<a href="/2015/06/24/checklist-for-contracts/">
<div>2015 06 24 Checklist for contracts </div>
</a>
<a href="/2015/06/23/the-state-of-mind-of-travelling/">
<div>2015 06 23 The state of mind of traveling </div>
</a>
<a href="/2015/06/22/do-it-now/">
<div>2015 06 22 Do it now </div>
</a>
<a href="/2015/06/21/making-modules-for-clojureclojurescript/">
<div>2015 06 21 Making modules for Clojure/ClojureScript </div>
</a>
<a href="/2015/06/20/e5-a4-a9/">
<div>2015 06 20 天 </div>
</a>
<a href="/2015/06/19/coding-tips/">
<div>2015 06 19 Coding tips </div>
</a>
<a href="/2015/06/18/dancing-connection/">
<div>2015 06 18 Dancing connection </div>
</a>
<a href="/2015/06/17/on-social-media/">
<div>2015 06 17 On social media </div>
</a>
<a href="/2015/06/16/half-monthly-review-2015-11/">
<div>2015 06 16 Half-monthly review 2015-11 </div>
</a>
<a href="/2015/06/15/regular-review/">
<div>2015 06 15 Regular review </div>
</a>
<a href="/2015/06/14/operational-requirements/">
<div>2015 06 14 Operational requirements </div>
</a>
<a href="/2015/06/13/why-deliver-as-open-source/">
<div>2015 06 13 Why deliver as open source </div>
</a>
<a href="/2015/06/12/parkinsons-law/">
<div>2015 06 12 Parkinsons law </div>
</a>
<a href="/2015/06/11/open-danish-bibliographic-data-and-semantic-markup/">
<div>2015 06 11 Open Danish bibliographic data, and semantic markup </div>
</a>
<a href="/2015/06/10/network-of-gratitude/">
<div>2015 06 10 Network of gratitude </div>
</a>
<a href="/2015/06/09/sorting-photos-with-linux-shell-scripting/">
<div>2015 06 09 Sorting photos with linux shell scripting </div>
</a>
<a href="/2015/06/08/intuitive-vs-sensing/">
<div>2015 06 08 Intuitive vs sensing </div>
</a>
<a href="/2015/06/07/an-efficient-weekday/">
<div>2015 06 07 An efficient weekday </div>
</a>
<a href="/2015/06/06/personal-writing/">
<div>2015 06 06 Personal writing </div>
</a>
<a href="/2015/06/05/strategic-vs-tactical-thinking/">
<div>2015 06 05 Strategic vs tactical thinking </div>
</a>
<a href="/2015/06/04/why-clojurescript/">
<div>2015 06 04 Why ClojureScript? </div>
</a>
<a href="/2015/06/03/dancing-in-copenhagen/">
<div>2015 06 03 Dancing in Copenhagen </div>
</a>
<a href="/2015/06/02/the-challenge-of-daily-writing/">
<div>2015 06 02 The challenge of daily writing. </div>
</a>
<a href="/2015/05/13/barefoot-tango/">
<div>2015 05 13 Barefoot tango </div>
</a>
<a href="/2014/07/01/pricing-scale/">
<div>2014 07 01 Pricing scale </div>
</a>
<a href="/2012/03/18/presentation-evaluation/">
<div>2012 03 18 Presentation evaluation </div>
</a>
<a href="/2006/07/01/fototips/">
<div>2006 07 01 Fototips </div>
</a>
<a href="/2005/07/01/skrivetips/">
<div>2005 07 01 Skrivetips </div>
</a>
</div>
